module(load="imudp")
input(type="imudp" port="514" address="192.168.8.210")

template(name="HomeNetworkFlintLog" type="string" string="/var/log/home-network/%fromhost-ip%.log")

if ($fromhost-ip == "192.168.8.1") then {
  action(type="omfile" file="/var/log/home-network/flint-cabinet.log")
  stop
}
if ($fromhost-ip == "192.168.8.113") then {
  action(type="omfile" file="/var/log/home-network/flint-office.log")
  stop
}
if ($fromhost-ip == "192.168.8.246") then {
  action(type="omfile" file="/var/log/home-network/flint-school.log")
  stop
}
